# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: signer

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 8 * * ?'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: install dependencies
      run: yarn
    - name: set env and run script
      env:
        user: ${{secrets.user}}
        pass: ${{secrets.pass}}
        to: ${{secrets.to}}
        cookie: ${{secrets.cookie}}
      run: user=${user} pass=${pass} to=${to} cookie=${cookie} node index.js
